version: '3.8'
services:
  db:
    image: postgres:13
    container_name: emergency_db
    environment:
      POSTGRES_USER: your_db_user
      POSTGRES_PASSWORD: your_db_password
      POSTGRES_DB: emergency_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  backend:
    build: .
    container_name: emergency_backend
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://your_db_user:your_db_password@db:5432/emergency_db?schema=public
    depends_on:
      - db
volumes:
  postgres_data: